server:
  port: 8084
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/BlogDB?characterEncoding=utf-8&useSSL=false&useTimezone=true
    username: root
    password: 153226
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB102Dialect
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  custom:
    file-upload-path: C:\Users\wang.weiran\Documents\code\wwr-blog\upload
    admin-username: wwr
    admin-password-hash: 82c9d6ef5c099fbc6e6094d4cf4c1771
    admin-password-salt: d2e37e3c92f651a6a554088573427b76
    admin-email: iswangwr@gmail.com
    jwt-key: test-key
